In [87]:
import pandas as pd

In [88]:
df1=pd.read_csv('trial.csv')
df2=pd.read_csv('audit.csv')

In [89]:
df1.shape

(776, 18)

In [90]:
df2.shape

(776, 27)

In [91]:
df1.head()

Sector_score LOCATION_ID  PARA_A  SCORE_A  PARA_B  SCORE_B  TOTAL  numbers  \
0          3.89          23    4.18        6    2.50        2   6.68      5.0   
1          3.89           6    0.00        2    4.83        2   4.83      5.0   
2          3.89           6    0.51        2    0.23        2   0.74      5.0   
3          3.89           6    0.00        2   10.80        6  10.80      6.0   
4          3.89           6    0.00        2    0.08        2   0.08      5.0   

   Marks  Money_Value  MONEY_Marks  District  Loss  LOSS_SCORE  History  \
0      2         3.38            2         2     0           2        0   
1      2         0.94            2         2     0           2        0   
2      2         0.00            2         2     0           2        0   
3      6        11.75            6         2     0           2        0   
4      2         0.00            2         2     0           2        0   

   History_score  Score  Risk  
0              2    2.4     1  
1              2    2.0     0  
2              2    2.0     0  
3              2    4.4     1  
4              2    2.0     0

In [92]:
df2.head()

Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  Risk_B  \
0          3.89          23    4.18      0.6   2.508    2.50      0.2   0.500   
1          3.89           6    0.00      0.2   0.000    4.83      0.2   0.966   
2          3.89           6    0.51      0.2   0.102    0.23      0.2   0.046   
3          3.89           6    0.00      0.2   0.000   10.80      0.6   6.480   
4          3.89           6    0.00      0.2   0.000    0.08      0.2   0.016   

   TOTAL  numbers  ...   RiSk_E  History  Prob  Risk_F  Score  Inherent_Risk  \
0   6.68      5.0  ...      0.4        0   0.2     0.0    2.4          8.574   
1   4.83      5.0  ...      0.4        0   0.2     0.0    2.0          2.554   
2   0.74      5.0  ...      0.4        0   0.2     0.0    2.0          1.548   
3  10.80      6.0  ...      0.4        0   0.2     0.0    4.4         17.530   
4   0.08      5.0  ...      0.4        0   0.2     0.0    2.0          1.416   

   CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
0           0.4             0.5      1.7148     1  
1           0.4             0.5      0.5108     0  
2           0.4             0.5      0.3096     0  
3           0.4             0.5      3.5060     1  
4           0.4             0.5      0.2832     0  

[5 rows x 27 columns]

In [93]:
df1.columns

Index(['Sector_score', 'LOCATION_ID', 'PARA_A', 'SCORE_A', 'PARA_B', 'SCORE_B',
       'TOTAL', 'numbers', 'Marks', 'Money_Value', 'MONEY_Marks', 'District',
       'Loss', 'LOSS_SCORE', 'History', 'History_score', 'Score', 'Risk'],
      dtype='object')

In [94]:
df2.columns

Index(['Sector_score', 'LOCATION_ID', 'PARA_A', 'Score_A', 'Risk_A', 'PARA_B',
       'Score_B', 'Risk_B', 'TOTAL', 'numbers', 'Score_B.1', 'Risk_C',
       'Money_Value', 'Score_MV', 'Risk_D', 'District_Loss', 'PROB', 'RiSk_E',
       'History', 'Prob', 'Risk_F', 'Score', 'Inherent_Risk', 'CONTROL_RISK',
       'Detection_Risk', 'Audit_Risk', 'Risk'],
      dtype='object')

In [95]:
df1.describe()

Sector_score      PARA_A     SCORE_A       PARA_B     SCORE_B  \
count    776.000000  776.000000  776.000000   776.000000  776.000000   
mean      20.184536    2.450194    3.512887    10.799988    3.131443   
std       24.319017    5.678870    1.740549    50.083624    1.698042   
min        1.850000    0.000000    2.000000     0.000000    2.000000   
25%        2.370000    0.210000    2.000000     0.000000    2.000000   
50%        3.890000    0.875000    2.000000     0.405000    2.000000   
75%       55.570000    2.480000    6.000000     4.160000    4.000000   
max       59.850000   85.000000    6.000000  1264.630000    6.000000   

             TOTAL     numbers       Marks  Money_Value  MONEY_Marks  \
count   776.000000  776.000000  776.000000   775.000000   776.000000   
mean     13.218481    5.067655    2.237113    14.137631     2.909794   
std      51.312829    0.264449    0.803517    66.606519     1.597452   
min       0.000000    5.000000    2.000000     0.000000     2.000000   
25%       0.537500    5.000000    2.000000     0.000000     2.000000   
50%       1.370000    5.000000    2.000000     0.090000     2.000000   
75%       7.707500    5.000000    2.000000     5.595000     4.000000   
max    1268.910000    9.000000    6.000000   935.030000     6.000000   

         District        Loss  LOSS_SCORE     History  History_score  \
count  776.000000  776.000000  776.000000  776.000000     776.000000   
mean     2.505155    0.029639    2.061856    0.104381       2.167526   
std      1.228678    0.184280    0.375080    0.531031       0.679869   
min      2.000000    0.000000    2.000000    0.000000       2.000000   
25%      2.000000    0.000000    2.000000    0.000000       2.000000   
50%      2.000000    0.000000    2.000000    0.000000       2.000000   
75%      2.000000    0.000000    2.000000    0.000000       2.000000   
max      6.000000    2.000000    6.000000    9.000000       6.000000   

            Score        Risk  
count  776.000000  776.000000  
mean     2.702577    0.626289  
std      0.858923    0.484100  
min      2.000000    0.000000  
25%      2.000000    0.000000  
50%      2.400000    1.000000  
75%      3.250000    1.000000  
max      5.200000    1.000000

In [96]:
df2.describe()

Sector_score      PARA_A     Score_A      Risk_A       PARA_B  \
count    776.000000  776.000000  776.000000  776.000000   776.000000   
mean      20.184536    2.450194    0.351289    1.351029    10.799988   
std       24.319017    5.678870    0.174055    3.440447    50.083624   
min        1.850000    0.000000    0.200000    0.000000     0.000000   
25%        2.370000    0.210000    0.200000    0.042000     0.000000   
50%        3.890000    0.875000    0.200000    0.175000     0.405000   
75%       55.570000    2.480000    0.600000    1.488000     4.160000   
max       59.850000   85.000000    0.600000   51.000000  1264.630000   

          Score_B      Risk_B        TOTAL     numbers   Score_B.1  \
count  776.000000  776.000000   776.000000  776.000000  776.000000   
mean     0.313144    6.334008    13.218481    5.067655    0.223711   
std      0.169804   30.072845    51.312829    0.264449    0.080352   
min      0.200000    0.000000     0.000000    5.000000    0.200000   
25%      0.200000    0.000000     0.537500    5.000000    0.200000   
50%      0.200000    0.081000     1.370000    5.000000    0.200000   
75%      0.400000    1.840500     7.707500    5.000000    0.200000   
max      0.600000  758.778000  1268.910000    9.000000    0.600000   

          ...          RiSk_E     History        Prob      Risk_F       Score  \
count     ...      776.000000  776.000000  776.000000  776.000000  776.000000   
mean      ...        0.519072    0.104381    0.216753    0.053608    2.702577   
std       ...        0.290312    0.531031    0.067987    0.305835    0.858923   
min       ...        0.400000    0.000000    0.200000    0.000000    2.000000   
25%       ...        0.400000    0.000000    0.200000    0.000000    2.000000   
50%       ...        0.400000    0.000000    0.200000    0.000000    2.400000   
75%       ...        0.400000    0.000000    0.200000    0.000000    3.250000   
max       ...        2.400000    9.000000    0.600000    5.400000    5.200000   

       Inherent_Risk  CONTROL_RISK  Detection_Risk  Audit_Risk        Risk  
count     776.000000    776.000000           776.0  776.000000  776.000000  
mean       17.680612      0.572680             0.5    7.168158    0.393041  
std        54.740244      0.444581             0.0   38.667494    0.488741  
min         1.400000      0.400000             0.5    0.280000    0.000000  
25%         1.583500      0.400000             0.5    0.316700    0.000000  
50%         2.214000      0.400000             0.5    0.555600    0.000000  
75%        10.663500      0.400000             0.5    3.249900    1.000000  
max       801.262000      5.800000             0.5  961.514400    1.000000  

[8 rows x 26 columns]

In [97]:
lis1=df1.columns
lis2=df2.columns

In [98]:
df3=df1
for lis in lis1:
    if lis in lis2:
        del df3[lis]

In [99]:
df3.shape

(776, 8)

In [100]:
# if you look carefully SCORE_A in df3 is sames as Score_A in df2 except SCORE_A elements are sacled by a
#factor of 10

In [101]:
del df3['SCORE_A']
del df3['SCORE_B']
df3.shape

(776, 6)

In [102]:
df=pd.concat([df3, df2], axis=1)

In [103]:
df.shape

(776, 33)

In [104]:
df.head()

Marks  MONEY_Marks  District  Loss  LOSS_SCORE  History_score  \
0      2            2         2     0           2              2   
1      2            2         2     0           2              2   
2      2            2         2     0           2              2   
3      6            6         2     0           2              2   
4      2            2         2     0           2              2   

   Sector_score LOCATION_ID  PARA_A  Score_A  ...   RiSk_E  History  Prob  \
0          3.89          23    4.18      0.6  ...      0.4        0   0.2   
1          3.89           6    0.00      0.2  ...      0.4        0   0.2   
2          3.89           6    0.51      0.2  ...      0.4        0   0.2   
3          3.89           6    0.00      0.2  ...      0.4        0   0.2   
4          3.89           6    0.00      0.2  ...      0.4        0   0.2   

   Risk_F  Score  Inherent_Risk  CONTROL_RISK  Detection_Risk  Audit_Risk  \
0     0.0    2.4          8.574           0.4             0.5      1.7148   
1     0.0    2.0          2.554           0.4             0.5      0.5108   
2     0.0    2.0          1.548           0.4             0.5      0.3096   
3     0.0    4.4         17.530           0.4             0.5      3.5060   
4     0.0    2.0          1.416           0.4             0.5      0.2832   

   Risk  
0     1  
1     0  
2     0  
3     1  
4     0  

[5 rows x 33 columns]

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 33 columns):
Marks             776 non-null int64
MONEY_Marks       776 non-null int64
District          776 non-null int64
Loss              776 non-null int64
LOSS_SCORE        776 non-null int64
History_score     776 non-null int64
Sector_score      776 non-null float64
LOCATION_ID       776 non-null object
PARA_A            776 non-null float64
Score_A           776 non-null float64
Risk_A            776 non-null float64
PARA_B            776 non-null float64
Score_B           776 non-null float64
Risk_B            776 non-null float64
TOTAL             776 non-null float64
numbers           776 non-null float64
Score_B.1         776 non-null float64
Risk_C            776 non-null float64
Money_Value       775 non-null float64
Score_MV          776 non-null float64
Risk_D            776 non-null float64
District_Loss     776 non-null int64
PROB              776 non-null float64
RiSk_E       

In [106]:
#money value has missing value

In [107]:
df['Money_Value'].fillna((df['Money_Value'].mean()), inplace=True)

In [108]:
y_reg=df['Audit_Risk']
y_clf=df['Risk']

In [109]:
del df['Audit_Risk']
del df['Risk']

In [110]:
X=df

In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y_reg, test_size=0.30, random_state=42)
X_train1, X_test1, y_train1, y_test1 = train_test_split( X, y_clf, test_size=0.30, random_state=42)


In [112]:
drop1=['Risk_A','Risk_B','Risk_C','Risk_D','RiSk_E','Risk_F']
for var in drop1:
    del X_train[var]
    del X_test[var]
    del X_train1[var]
    del X_test1[var]
    

In [113]:
drop2=['History','Loss','TOTAL','Score_B','Score','District_Loss','District','LOCATION_ID']
for var in drop2:
    del X_train[var]
    del X_test[var]
    del X_train1[var]
    del X_test1[var]

In [114]:
drop3=['numbers','Score_B.1','Score_MV','PROB','Money_Value','Prob','Detection_Risk','Score_A','CONTROL_RISK','Inherent_Risk']
for var in drop3:
    del X_train[var]
    del X_test[var]
    del X_train1[var]
    del X_test1[var]

In [115]:
X_train.shape

(543, 7)

In [116]:
X_train1.shape

(543, 7)

In [117]:
X_train.head()

Marks  MONEY_Marks  LOSS_SCORE  History_score  Sector_score  PARA_A  \
335      2            2           2              2          2.37    0.00   
110      2            2           2              2          3.89    2.63   
82       2            2           2              2          3.89    0.00   
51       2            2           2              2          3.89    0.00   
763      2            2           2              2         55.57    0.02   

     PARA_B  
335    0.00  
110    2.55  
82     0.00  
51    18.05  
763    0.00

In [118]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
bag_reg = BaggingRegressor(
    DecisionTreeRegressor(random_state=42), n_estimators=50,
    max_samples=200, bootstrap=True, n_jobs=-1, random_state=42)
bag_reg.fit(X_train, y_train)
y_pred = bag_reg.predict(X_test)
y_pred1 = bag_reg.predict(X_train)
from sklearn.metrics import r2_score
r2_score(y_train,y_pred1)

0.6760183230583827

In [119]:
import numpy as np
y_train=np.log1p(y_train)
y_test=np.log1p(y_test)

In [120]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.fit_transform(X_test)
X_train1=scalar.fit_transform(X_train1)
X_test1=scalar.fit_transform(X_test1)

/home/sanjay/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/sanjay/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/home/sanjay/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/sanjay/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/home/sanjay/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: Da

In [130]:
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import Ridge
bag_reg = BaggingRegressor(
    Ridge(alpha=30), n_estimators=50,
    max_samples=150, bootstrap=True, n_jobs=-1, random_state=42)
bag_reg.fit(X_train, y_train)
y_pred = bag_reg.predict(X_test)
y_pred1 = bag_reg.predict(X_train)

In [131]:
from sklearn.metrics import r2_score
r2_score(y_train,y_pred1)

0.8633444925114162

In [132]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7864894246304325

In [142]:
from sklearn.ensemble import BaggingRegressor
from sklearn.svm import SVR

bag_reg = BaggingRegressor(
    SVR(gamma='scale', C=.50, epsilon=0.1), n_estimators=50,
    max_samples=100, bootstrap=True, n_jobs=-1, random_state=42)
bag_reg.fit(X_train, y_train)
y_pred = bag_reg.predict(X_test)
y_pred1 = bag_reg.predict(X_train)

In [143]:
from sklearn.metrics import r2_score
r2_score(y_train,y_pred1)

0.7876877262331567

In [144]:
r2_score(y_test,y_pred)

0.7727849401149263

In [41]:
# C=.5 gives very good generalization over data
#now let's do pasting for that there is no bootstrapping pasting

In [154]:
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import Ridge
bag_reg = BaggingRegressor(
    Ridge(alpha=30), n_estimators=50,
    max_samples=150, bootstrap=False, n_jobs=-1, random_state=42)
bag_reg.fit(X_train, y_train)
y_pred = bag_reg.predict(X_test)
y_pred1 = bag_reg.predict(X_train)

In [155]:
from sklearn.metrics import r2_score
r2_score(y_train,y_pred1)

0.8648194876818586

In [156]:
r2_score(y_test,y_pred)

0.788520868850821

In [169]:
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import Lasso
bag_reg = BaggingRegressor(
    Lasso(alpha=0.01), n_estimators=50,
    max_samples=190, bootstrap=False, n_jobs=-1, random_state=42)
bag_reg.fit(X_train, y_train)
y_pred = bag_reg.predict(X_test)
y_pred1 = bag_reg.predict(X_train)

In [170]:
from sklearn.metrics import r2_score
r2_score(y_train,y_pred1)

0.8518561230545622

In [171]:
r2_score(y_test,y_pred)

0.740878768780446

In [172]:
from sklearn.ensemble import AdaBoostRegressor

ada_reg = AdaBoostRegressor(
    Ridge(alpha=6), n_estimators=200, learning_rate=0.5, random_state=42)
ada_reg.fit(X_train, y_train)
y_pred = ada_reg.predict(X_test)
y_pred1 = ada_reg.predict(X_train)

In [173]:
r2_score(y_train,y_pred1)

0.8811986258541681

In [174]:
r2_score(y_test,y_pred)

0.7558595730113876

In [51]:
#GradientBoosting

In [175]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=10, solver="cholesky")
ridge_reg.fit(X_train, y_train)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='cholesky', tol=0.001)

In [176]:
y2 = y_train - ridge_reg.predict(X_train)
ridge_reg1 = Ridge(alpha=1, solver="cholesky")
ridge_reg1.fit(X_train, y2)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='cholesky', tol=0.001)

In [177]:
y3 = y2 - ridge_reg1.predict(X_train)
ridge_reg2 = Ridge(alpha=6, solver="cholesky")
ridge_reg2.fit(X_train, y3)

Ridge(alpha=6, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='cholesky', tol=0.001)

In [178]:
y_pred = sum(reg.predict(X_test) for reg in (ridge_reg, ridge_reg1, ridge_reg2))

In [179]:
y_pred1 = sum(reg.predict(X_train) for reg in (ridge_reg, ridge_reg1, ridge_reg2))

In [180]:
r2_score(y_train,y_pred1)

0.8737453160578845

In [181]:
r2_score(y_test,y_pred)

0.7684449702905649

In [187]:
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=5)
X_trainpca = sklearn_pca.fit_transform(X_train)
X_testpca = sklearn_pca.fit_transform(X_test)

In [188]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1, solver="cholesky")
ridge_reg.fit(X_trainpca, y_train)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='cholesky', tol=0.001)

In [189]:
y_pred1=ridge_reg.predict(X_trainpca)
y_pred=ridge_reg.predict(X_testpca)

In [190]:
r2_score(y_train,y_pred1)

0.8425164269734766

In [191]:
r2_score(y_test,y_pred)

0.7668388874444638

In [64]:
#here  pass x_train_pca and testpca as an arguments for PCA inputs

In [65]:
#classification

In [66]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
bag_clf = BaggingClassifier(
SVC(kernel='linear',C=10), n_estimators=500,
max_samples=100, bootstrap=True, n_jobs=-1
)
bag_clf.fit(X_train1, y_train1)
y_pred = bag_clf.predict(X_test1)
y_pred1=bag_clf.predict(X_train1)

In [67]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test1, y_pred)
mat
#testing

array([[139,   2],
       [ 22,  70]])

In [68]:
mat = confusion_matrix(y_train1, y_pred1)
mat
#training

array([[327,   3],
       [ 40, 173]])

In [69]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred))

Accuracy: 0.8969957081545065


In [70]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
bag_clf = BaggingClassifier(
KNeighborsClassifier(n_neighbors=6), n_estimators=500,
max_samples=100, bootstrap=True, n_jobs=-1
)
bag_clf.fit(X_train1, y_train1)
y_pred = bag_clf.predict(X_test1)
y_pred1=bag_clf.predict(X_train1)

In [71]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test1, y_pred)
mat
#testing

array([[135,   6],
       [ 23,  69]])

In [72]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred))

Accuracy: 0.8755364806866953


In [73]:
#pasting

In [74]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
bag_clf = BaggingClassifier(
KNeighborsClassifier(n_neighbors=6), n_estimators=500,
max_samples=100, bootstrap=False, n_jobs=-1
)
bag_clf.fit(X_train1, y_train1)
y_pred = bag_clf.predict(X_test1)
y_pred1=bag_clf.predict(X_train1)

In [75]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test1, y_pred)
mat

array([[135,   6],
       [ 23,  69]])

In [76]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred))

Accuracy: 0.8755364806866953


In [77]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
bag_clf = BaggingClassifier(
SVC(kernel='linear',C=20), n_estimators=500,
max_samples=100, bootstrap=False, n_jobs=-1
)
bag_clf.fit(X_train1, y_train1)
y_pred = bag_clf.predict(X_test1)
y_pred1=bag_clf.predict(X_train1)

In [78]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test1, y_pred)
mat

array([[141,   0],
       [ 23,  69]])

In [79]:
#adaboost

In [80]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(
    SVC(kernel='linear',C=10),algorithm='SAMME', n_estimators=150, learning_rate=0.5, random_state=42)
ada_clf.fit(X_train1, y_train1)
y_pred = ada_clf.predict(X_test1)
y_pred1=ada_clf.predict(X_train1)

In [81]:
mat = confusion_matrix(y_test1, y_pred)
mat

array([[134,   7],
       [ 20,  72]])

In [82]:
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=2)
X_trainpca = sklearn_pca.fit_transform(X_train1)
X_testpca = sklearn_pca.fit_transform(X_test1)

In [83]:
from sklearn.svm import SVC
svc = SVC(kernel='linear',C=10)
svc.fit(X_trainpca,y_train1)
y_pred = svc.predict(X_testpca)
y_pred1=svc.predict(X_trainpca)

In [84]:
mat = confusion_matrix(y_test1, y_pred)
mat

array([[135,   6],
       [ 23,  69]])

In [85]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=15)
model.fit(X_trainpca,y_train1)
y_pred = model.predict(X_testpca)
y_pred1=model.predict(X_trainpca)

In [86]:
mat = confusion_matrix(y_test1, y_pred)
mat

array([[135,   6],
       [ 21,  71]])